### ISSUE TITLE
unlv_marc_exporter no longer works / using archivesspace v3.3

### ISSUE THREAD

**Issue by jrhodesung** [UNLV-Libraries/ArchivesSpace-authority-project#25]
We have been upgrading our archivesspace instance as new updates are available. I've recently been made aware that the XML exports were no longer working. Removing the unlv_marc_exporter plugin allows XML files to be exported again. 

With the plugin installed we are getting an error "This page contains the following errors: error on linie 1 at column 1: Document is empty..." 

The XML document says "{"error":"wrong number of arguments (given 4, expected 1): /usr/lib/archivesspace/plugins/unlv_marc_exporter/backend/model/unlv_marc21_exporter.rb:455:...

**Comment by Gii2000** [comment]
Thank you. We are now maintaining unlv_marc_exporter at https://github.com/UNLV-Libraries/unlv_marc_exporter, where I have fixed the issue.

**Comment by jrhodesung** [comment]
Thank you! Our Archivists will be happy to have this plugin back in production!
